/* ============================================================
   /income-tax FAQ — moved out of IncomeTaxPage (Oct 2026) so the /faq hub can
   reuse the exact same answers. App.jsx imports this statically (the tax page
   is in the main bundle already, so nothing grows); the /faq page imports it
   from its own lazy chunk. Rules quoted here are the ones the calculator uses
   (Finance Act 2026; FY 2025-26 and FY 2026-27). Do not edit figures without a
   cited source.
   ============================================================ */
export const TAX_FAQ = [
  { q: "Which financial year should I calculate — FY 2025-26 or FY 2026-27?", a: "If you're filing a return in 2026, you need FY 2025-26 (income earned 1 July 2025 to 30 June 2026, assessment year 2026-27) — that's the return due by 30 November 2026. Use FY 2026-27 only to plan the year you're currently earning in. This calculator does both; pick the year at the top." },
  { q: "What is the tax-free income limit in Bangladesh?", a: "For FY 2025-26 the general tax-free limit is ৳3,75,000 — ৳4,25,000 for women and senior citizens (65+), ৳5,00,000 for persons with disability and third-gender taxpayers, and ৳5,25,000 for gazetted war-wounded freedom fighters. For FY 2026-27 the general limit rises to ৳4,00,000. Income above your limit is taxed on a slab basis." },
  { q: "How is the income tax rebate calculated?", a: "Your rebate is the lowest of three numbers: a percentage of your eligible investment, 3% of your taxable income, and a statutory ceiling. For FY 2025-26 it's 15% of investment with a ৳10,00,000 ceiling; for FY 2026-27 the rate was cut to 10% with a ৳7,50,000 ceiling. It's subtracted straight from your calculated tax." },
  { q: "Why doesn't my employer's tax sheet match this calculator?", a: "Almost always one of three things. First, fiscal year — a June 2026 payslip uses FY 2025-26 rules, not FY 2026-27. Second, the rebate rate changed from 15% to 10% between those years. Third, income base — corporate payroll often includes the employer's provident-fund contribution in total income before the one-third exemption, so enter your total income, not just take-home pay." },
  { q: "What investments qualify for the tax rebate?", a: "Sanchayapatra (national savings certificates), DPS (deposit pension schemes), listed mutual funds and shares, approved life-insurance premiums, and provident-fund contributions. Sanchayapatra and a bank DPS are the two most popular and lowest-risk options." },
  { q: "What is the minimum income tax in Bangladesh?", a: "If your income crosses the tax-free threshold, the minimum tax is ৳5,000 in Dhaka North, Dhaka South and Chattogram city corporations — ৳4,000 in other city corporations and ৳3,000 elsewhere — or ৳1,000 for a first-time filer whose taxable income is under ৳4,50,000. A rebate can't reduce your tax below this floor." },
  { q: "What is the deadline to file my tax return?", a: "For individual taxpayers, 'Tax Day' is 30 November. Filing between 1 July and 30 September earns a 5% rebate on your tax (up to ৳25,000); filing after the deadline adds a 2%–5% surcharge with a minimum penalty. Earlier is cheaper." },
  { q: "How much investment do I need to make to get the maximum rebate?", a: "It depends on the year. In FY 2025-26 you earn 15% back and the rebate caps at 3% of taxable income, so roughly 20% of taxable income maximises it. In FY 2026-27 the rate dropped to 10%, so you need about 30%. Our calculator shows your exact optimum figure for the year you select." },
  { q: "Do women and senior citizens pay less tax?", a: "Effectively yes — they get a higher tax-free threshold (৳4,25,000 vs ৳3,75,000 general in FY 2025-26), so the first slab of tax starts later. Persons with disability, third-gender taxpayers and freedom fighters get even higher thresholds." },
  { q: "Is Sanchayapatra interest still taxable?", a: "Source tax (5–10%) is deducted on Sanchayapatra profit at payout, and the interest is part of your total income. But the investment itself still qualifies for the rebate, and it remains the highest safe return in Bangladesh — see our Sanchayapatra page for current rates." },
  { q: "Where do I actually file my return?", a: "Filing happens on the government's own e-Return system, run by the National Board of Revenue (NBR). FinDesh doesn't file for you — we help you understand and plan. When you're ready to file, head to the official NBR e-Return portal." },
];
